.PHONY: clean All

All:
	@echo "----------Building project:[ SoftUni - Debug ]----------"
	@"$(MAKE)" -f  "SoftUni.mk"
clean:
	@echo "----------Cleaning project:[ SoftUni - Debug ]----------"
	@"$(MAKE)" -f  "SoftUni.mk" clean
